export const AUTH_LOGIN = 'AUTH_LOGIN';

export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';

export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export const AUTH_SET_LOGGEDIN = 'AUTH_SET_LOGGEDIN';